upstream:
  default:
    - 1.1.1.1
    - 8.8.8.8

blocking:
  groups:
    # Work hours: 8AM-8PM - Block entertainment only
    work:
      blockLists:
        - file:///app/lists/blocklists/entertainment.txt
      activation:
        start: "08:00"
        end: "20:00"
      
    # Evening/night: 8PM-10AM - Block social media & gaming
    night:
      blockLists:
        - file:///app/lists/blocklists/social-media.txt
        - file:///app/lists/blocklists/gaming.txt
      activation:
        start: "20:00"
        end: "10:00"
      
    # Free time: No blocking
    free:
      blockLists: []

  # Default group when no time matches
  defaultGroup: free
  
  # 10-second delay for social media
  blockingTimeout: 10s

port: 53
httpPort: 4000

ratelimit: 15
queryLog:
  type: none

logging:
  level: error
