upstreams:
  groups:
    default:
      - 1.1.1.1
      - 8.8.8.8

blocking:
  denylists:
    work:
      - file:///app/lists/blocklists/entertainment.txt
    night:
      - file:///app/lists/blocklists/social-media.txt
      - file:///app/lists/blocklists/gaming.txt
    free: []

  clientGroupsBlock:
    default:
      - free
    192.168.0.0/16:
      - work
    10.0.0.0/8:
      - night

  blockTTL: 10s

ports:
  dns: 53
  http: 4000

queryLog:
  type: none

log:
  level: error
